MediaStreaming/ApiApp/urls.py
from django.urls import path,include

from rest_framework import routers
from ApiApp import views,movies,users,people,torrent

from rest_framework.urlpatterns import format_suffix_patterns


# router = routers.DefaultRouter()

# router.register("movies",views.MovieApi)
# router.register("users",views.UserApi)
# router.urls
# urlpatterns = [
#     path('', include(router.urls)),
    
# ]
app_name = 'ApiApp'

urlpatterns = [
    path('', views.ApiHome.as_view()),
    path('movie/now_playing/', movies.get_now_playing_movies.as_view()),
    path('movie/top_rated/', movies.get_top_rated_movies.as_view()),
    path('movie/popular/', movies.get_popular_movies.as_view()),
    path('movie/new_releases/', movies.get_new_releases.as_view()),

    path('movie/poster/<int:movie_id>', movies.get_movie_poster.as_view(),name="movie_poster"),
    path('movie/poster_urls/<int:movie_id>', movies.get_movie_poster_urls.as_view()),
    path('movie/backdrop/<int:movie_id>', movies.get_movie_backdrop.as_view(),name="movie_backdrop"),
    path('movie/backdrop_urls/<int:movie_id>', movies.get_movie_backdrop_urls.as_view()),
    path('movie/details/<int:movie_id>', movies.get_complete_movie_details.as_view(),name='movie_details'),
    path('movie/credits/<int:movie_id>', movies.movie_credits.as_view()),
    path('movie/similar/<int:movie_id>', movies.similar_movies.as_view()),

    path('search/movie/', movies.search_movie.as_view()),


    path("user/",users.Users.as_view()),
    path("user/verify/",users.updateVerifiedUser.as_view()),

    path("user/history/<str:pk>",users.Users_History.as_view()),
    path("user/favourites/<str:pk>",users.Users_Favourites.as_view()),
    path("user/watchlist/<str:pk>",users.Users_Watchlist.as_view()),

    path('file/torrent/<int:torrent_id>',torrent.get_torrent_file.as_view()),


    path('people/profile_picture/<int:people_id>',people.get_people_profile_picture.as_view())


]

urlpatterns = format_suffix_patterns(urlpatterns)

MediaStreaming/HomeApp/urls.py
from django.urls import path,include
from . import views


app_name = 'HomeApp'


urlpatterns = [   
   path('', views.index , name="index"),
    
]

MediaStreaming/ManagerApp/urls.py
from django.urls import path,include
from . import views,movies,upload_media,manage_sources

app_name = 'ManagerApp'


urlpatterns = [
   
    path('login/', views.loginPage,name="loginPage"),
    path('logout/', views.logoutUser,name="logoutUser"),

    path('', views.dashboard , name="dashboard"),
    
    path('movies/', movies.movie_dashboard , name="movie_dashboard"),
    path('movie/<int:movie_id>', movies.movie_details_page , name="movie_details"),
    path('movie/add_new', movies.add_new_movie , name="add_new_movie"),
    path('movie/add_new/search_result/<int:movie_id>', movies.view_tmdb_result , name="view_tmdb_result"),
    path('movie/add_movie_to_system/<int:movie_id>', movies.add_movie_to_system , name="add_movie_to_system"),
    path('movie/manage_sources', manage_sources.manage_sources_movies , name="manage_sources_movies"),
    path('movie/manage_sources/add_new_firebase_credentials', manage_sources.add_new_firebase_credentials , name="add_new_firebase_credentials"),


    
    path('upload_media/<int:media_id>', upload_media.upload_media_page , name="upload_media"),
    path('upload_media_firebase/<int:media_id>', upload_media.upload_media_firebase , name="upload_media_firebase"),


]

MediaStreaming/MediaStreaming/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/",include('ApiApp.urls')),
    path("",include('HomeApp.urls')),
    path("managerapp/",include('ManagerApp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MediaStreaming/HomeApp/models.py
from django.db import models

# Create your models here.

MediaStreaming/HomeApp/views.py
from django.shortcuts import render



def index(request):

    context = {
        "page_title ":"Home App"
    }
    return render(request,'HomeApp/index.html',context)# Create your views here.

MediaStreaming/HomeApp/templates/HomeApp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

    <title>
        {% block title %}
        {{ page_title|default:"Untitled Page" }}
        {% endblock title %}
    </title>



</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Movie Streaming</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Api</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ManagerApp:dashboard'%}">Manager App</a>
                </li>

<!-- 
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li> -->

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</body>

</html>