MediaStreaming/ApiApp/urls.py
from django.urls import path,include

from rest_framework import routers
from ApiApp import views,movies,users,people,torrent

from rest_framework.urlpatterns import format_suffix_patterns


# router = routers.DefaultRouter()

# router.register("movies",views.MovieApi)
# router.register("users",views.UserApi)
# router.urls
# urlpatterns = [
#     path('', include(router.urls)),
    
# ]
app_name = 'ApiApp'

urlpatterns = [
    path('', views.ApiHome.as_view()),
    path('movie/now_playing/', movies.get_now_playing_movies.as_view()),
    path('movie/top_rated/', movies.get_top_rated_movies.as_view()),
    path('movie/popular/', movies.get_popular_movies.as_view()),
    path('movie/new_releases/', movies.get_new_releases.as_view()),

    path('movie/poster/<int:movie_id>', movies.get_movie_poster.as_view(),name="movie_poster"),
    path('movie/poster_urls/<int:movie_id>', movies.get_movie_poster_urls.as_view()),
    path('movie/backdrop/<int:movie_id>', movies.get_movie_backdrop.as_view(),name="movie_backdrop"),
    path('movie/backdrop_urls/<int:movie_id>', movies.get_movie_backdrop_urls.as_view()),
    path('movie/details/<int:movie_id>', movies.get_complete_movie_details.as_view(),name='movie_details'),
    path('movie/credits/<int:movie_id>', movies.movie_credits.as_view()),
    path('movie/similar/<int:movie_id>', movies.similar_movies.as_view()),

    path('search/movie/', movies.search_movie.as_view()),


    path("user/",users.Users.as_view()),
    path("user/verify/",users.updateVerifiedUser.as_view()),

    path("user/history/<str:pk>",users.Users_History.as_view()),
    path("user/favourites/<str:pk>",users.Users_Favourites.as_view()),
    path("user/watchlist/<str:pk>",users.Users_Watchlist.as_view()),

    path('file/torrent/<int:torrent_id>',torrent.get_torrent_file.as_view()),


    path('people/profile_picture/<int:people_id>',people.get_people_profile_picture.as_view())


]

urlpatterns = format_suffix_patterns(urlpatterns)

MediaStreaming/ManagerApp/urls.py
from django.urls import path,include
from . import views,movies,upload_media,manage_sources

app_name = 'ManagerApp'


urlpatterns = [
   
    path('login/', views.loginPage,name="loginPage"),
    path('logout/', views.logoutUser,name="logoutUser"),

    path('', views.dashboard , name="dashboard"),
    
    path('movies/', movies.movie_dashboard , name="movie_dashboard"),
    path('movie/<int:movie_id>', movies.movie_details_page , name="movie_details"),
    path('movie/add_new', movies.add_new_movie , name="add_new_movie"),
    path('movie/add_new/search_result/<int:movie_id>', movies.view_tmdb_result , name="view_tmdb_result"),
    path('movie/add_movie_to_system/<int:movie_id>', movies.add_movie_to_system , name="add_movie_to_system"),
    path('movie/manage_sources', manage_sources.manage_sources_movies , name="manage_sources_movies"),
    path('movie/manage_sources/add_new_firebase_credentials', manage_sources.add_new_firebase_credentials , name="add_new_firebase_credentials"),


    
    path('upload_media/<int:media_id>', upload_media.upload_media_page , name="upload_media"),
    path('upload_media_firebase/<int:media_id>', upload_media.upload_media_firebase , name="upload_media_firebase"),


]

MediaStreaming/MediaStreaming/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/",include('ApiApp.urls')),
    path("",include('HomeApp.urls')),
    path("managerapp/",include('ManagerApp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MediaStreaming/ManagerApp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Companies(models.Model):
    id = models.IntegerField(primary_key=True)
    description = models.TextField(blank=True, null=True)
    headquarters = models.TextField(blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    origin_country = models.CharField(max_length=10, blank=True, null=True)
    parent_company = models.CharField(max_length=50, blank=True, null=True)
    logo = models.TextField(blank=True, null=True)
    homepage = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'companies'


class Genres(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'genres'


class ImagesBackdrops(models.Model):
    backref_id = models.IntegerField(blank=True, null=True)
    image_category = models.CharField(max_length=10)
    image_data = models.BinaryField()
    aspect_ratio = models.FloatField(blank=True, null=True)
    heigth = models.FloatField(blank=True, null=True)
    width = models.FloatField(blank=True, null=True)
    iso_639_1 = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'images_backdrops'


class ImagesPosters(models.Model):
    backref_id = models.IntegerField(blank=True, null=True)
    image_category = models.CharField(max_length=10)
    image_data = models.BinaryField()
    aspect_ratio = models.FloatField(blank=True, null=True)
    heigth = models.FloatField(blank=True, null=True)
    width = models.FloatField(blank=True, null=True)
    iso_639_1 = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'images_posters'


class Movies(models.Model):
    
    adult = models.BooleanField(blank=True, null=True)
    id = models.IntegerField(primary_key=True)
    imdb_id = models.CharField(max_length=10, blank=True, null=True)
    original_language = models.CharField(max_length=10, blank=True, null=True)
    original_title = models.CharField(max_length=200, blank=True, null=True)
    overview = models.TextField(blank=True, null=True)
    release_date = models.DateField(blank=True, null=True)
    runtime = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=20, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    tagline = models.TextField(blank=True, null=True)
    date_created = models.DateField(blank=True, null=True)
    date_updated = models.DateField(blank=True, null=True)
    streamable = models.BooleanField(blank=True, null=True)
    torrent = models.BooleanField(blank=True, null=True)
    vote_average = models.FloatField(blank=True, null=True)
    vote_count = models.IntegerField(blank=True, null=True)
    popularity = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'movies'


class MoviesProductionCompanies(models.Model):
    movie = models.ForeignKey(Movies, models.DO_NOTHING)
    company = models.ForeignKey(Companies, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'movies_production_companies'


class MoviesToBackdrops(models.Model):
    movie = models.ForeignKey(Movies, models.DO_NOTHING, blank=True, null=True)
    backrop = models.ForeignKey(ImagesBackdrops, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'movies_to_backdrops'


class MoviesToGenres(models.Model):
    movie = models.ForeignKey(Movies, models.DO_NOTHING)
    genre = models.ForeignKey(Genres, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'movies_to_genres'


class MoviesToPosters(models.Model):
    movie = models.ForeignKey(Movies, models.DO_NOTHING, blank=True, null=True)
    poster = models.ForeignKey(ImagesPosters, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'movies_to_posters'


class MoviesToTorrents(models.Model):
    id = models.AutoField(primary_key=True)
    movie = models.ForeignKey(Movies, models.DO_NOTHING)
    torrent = models.ForeignKey('Torrents', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'movies_to_torrents'


class People(models.Model):
    id = models.IntegerField(primary_key=True)
    birthday = models.DateField(blank=True, null=True)
    known_for_department = models.CharField(max_length=200, blank=True, null=True)
    death_day = models.DateField(blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=100, blank=True, null=True)
    popularity = models.FloatField(blank=True, null=True)
    imdb_id = models.CharField(max_length=100, blank=True, null=True)
    homepage = models.CharField(max_length=100, blank=True, null=True)
    place_of_birth = models.CharField(max_length=100, blank=True, null=True)
    profile_picture = models.BinaryField(blank=True, null=True)
    biography = models.TextField(blank=True, null=True)
    adult = models.BooleanField(blank=True, null=True)
    profile_picture_path = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'people'


class PeopleAlsoKnownAs(models.Model):
    name = models.CharField(max_length=100)
    people = models.ForeignKey(People, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'people_also_known_as'


class SourceGoogleDrive(models.Model):
    quality = models.CharField(max_length=100, blank=True, null=True)
    backref_id = models.IntegerField()
    size_bytes = models.PositiveBigIntegerField(blank=True, null=True)
    preview_url = models.CharField(max_length=200)
    sharing_url = models.CharField(max_length=200)
    drive_file_id = models.CharField(max_length=100)
    path = models.CharField(max_length=100, blank=True, null=True)
    drive_folder_id = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=100, blank=True, null=True)
    filename = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'source_google_drive'


class Torrents(models.Model):
    url = models.TextField(blank=True, null=True)
    quality = models.CharField(max_length=15, blank=True, null=True)
    date_uploaded = models.DateField(blank=True, null=True)
    seeds = models.IntegerField(blank=True, null=True)
    peers = models.IntegerField(blank=True, null=True)
    size = models.CharField(max_length=20, blank=True, null=True)
    magent_url = models.TextField(blank=True, null=True)
    hash = models.TextField(blank=True, null=True)
    torrent_file = models.BinaryField(blank=True, null=True)
    torrent_source = models.CharField(max_length=20, blank=True, null=True)
    source_id = models.IntegerField(blank=True, null=True)
    size_bytes = models.IntegerField(blank=True, null=True)
    torrent_category = models.TextField(blank=True, null=True)
    backref_id = models.IntegerField(blank=True, null=True)


    class Meta:
        managed = False
        db_table = 'torrents'


class Users(models.Model):
    uid = models.CharField(primary_key=True, max_length=100)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)
    full_phone_number = models.CharField(max_length=200, blank=True, null=True)
    profile_picture = models.BinaryField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'users'


class UserFavourites(models.Model):
    uid = models.ForeignKey('Users', models.DO_NOTHING, db_column='uid')
    type = models.CharField(max_length=100)
    backref_id = models.IntegerField()
    date_created = models.DateTimeField()
    last_accessed = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'user__favourites'


class UserHistory(models.Model):
    uid = models.ForeignKey('Users', models.DO_NOTHING, db_column='uid')
    type = models.CharField(max_length=100)
    backref_id = models.IntegerField()
    date_created = models.DateTimeField()
    last_accessed = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'user__history'


class UserWatchlist(models.Model):
    uid = models.ForeignKey('Users', models.DO_NOTHING, db_column='uid')
    type = models.CharField(max_length=100)
    backref_id = models.IntegerField()
    date_created = models.DateTimeField()
    last_accessed = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'user__watchlist'

class FirebaseCredentials(models.Model):
    type = models.TextField()
    project_id = models.TextField()
    private_key_id = models.TextField()
    private_key = models.TextField()
    client_email = models.TextField()
    client_id = models.TextField()
    auth_uri = models.TextField()
    token_uri = models.TextField()
    auth_provider_x509_cert_url = models.TextField()
    client_x509_cert_url = models.TextField()
    owner_email = models.CharField(max_length=2000)

    class Meta:
        managed = False
        db_table = 'firebase__credentials'


class FirebaseMovies(models.Model):
    filename = models.CharField(max_length=200)

MediaStreaming/ManagerApp/forms.py
from django import forms
from .models import SourceGoogleDrive,FirebaseMovies,FirebaseCredentials

from django.core.validators import EmailValidator

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-control-user","id":"exampleInputEmail",'aria-describedby':"emailHelp",
                                                'placeholder':"Username or Email"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control form-control-user" ,"id":"exampleInputPassword", "placeholder":"Password"}))

    remember_me = forms.BooleanField(initial="False",label="Remember Me",required=False, widget=forms.CheckboxInput(attrs={"class":"custom-control-input" , "id":"customCheck" }))


class GoogleDriveSourceForm(forms.ModelForm):
    class Meta:
        model = SourceGoogleDrive
        fields = '__all__'


class FirebaseCredentialsForm(forms.Form):
    serviceAccount = forms.CharField(label="Service Account JSON",required= True,widget=forms.Textarea(attrs={"class":"form-control form-control-user","id":"exampleInputEmail",'aria-describedby':"emailHelp",
                                                'placeholder':"Paste Service Account JSON Here"}))
    owner_email = forms.EmailField(required =True,widget=forms.EmailInput(attrs={"class":"form-control form-control-user" ,"id":"exampleInputPassword", "placeholder":"Email"}),validators=[EmailValidator])

    
class FirebaseMoviesForm(forms.ModelForm):
    class Meta:
        model = FirebaseMovies
        fields = '__all__'

MediaStreaming/ManagerApp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from . import forms,models
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import psutil


def loginPage(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        # print(form)
        if form.is_valid():
            username = request.POST.get('username',"")
            password = request.POST.get('password',"")
            user = authenticate(request,username =username,password=password)
            if user is not None:
                login(request,user)
                return redirect("ManagerApp:dashboard")
            else:
                messages.error(request, 'Invalid Credintails')
                print("User  Error")


    form = forms.LoginForm(initial={'remember_me': False})
    context = {'title': "Manager App", 'form': form}
    return render(request,
    'ManagerApp/index.html',context)


def logoutUser(request):
    logout(request)
    return redirect("ManagerApp:loginPage")
    
@login_required(login_url="ManagerApp:loginPage")
def dashboard(request):
    movies = models.Movies.objects.count()



    context={'title': "Manager App - Dashborad",
        "total_movies":movies,
        "total_series":0,
        "pending_requests":0,
        "server_load":psutil.cpu_percent(),
        "cpu_usage":psutil.cpu_percent(),
        "ram_usage":psutil.virtual_memory().percent,
        "active_nav_item":"movies",
        "active_nav_item":"dashboard"}

    return render(request,'ManagerApp/dashboard.html',context)

import requests
def get_confirm_token(response):
    for key, value in response.cookies.items():
        if key.startswith('download_warning'):
            return value

    return None

def test(request):
    movie = models.Movies.objects.get(id=5)
    form = forms.FirebaseCredentialsForm()
    context = {
        "form":form
    }
    return render(request,'ManagerApp/test/test.html',context)

MediaStreaming/ManagerApp/templates/ManagerApp/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/2cf6a2c190.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <title>
        {% block title %}
        {{ page_title|default:"Untitled Page" }}
        {% endblock title %}
    </title>
</head>

<body>
    {% load static %}

    {% block content %}

    <p>Placeholder text in base template. Replace with page content.</p>

    {% endblock content %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ManagerApp/prebuild/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'ManagerApp/prebuild/js/sb-admin-2.min.js' %}"></script>
</body>

</html>

MediaStreaming/ManagerApp/templates/ManagerApp/dashboard.html
{% extends 'ManagerApp/dashboard_base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}

{% block page_content %}


<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard </h1>
        <!-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> -->
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Total Movies (System)</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total_movies }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fa fa-film fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Total Series (System)</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total_series }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fa fa-film fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">CPU Usage
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ server_load }}%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar" style="width: {{ server_load }}%"
                                            aria-valuenow="{{ server_load }}" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fa fa-server fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

                <!-- Earnings (Monthly) Card Example -->
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">ram_usage
                                    </div>
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-auto">
                                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ ram_usage }}%</div>
                                        </div>
                                        <div class="col">
                                            <div class="progress progress-sm mr-2">
                                                <div class="progress-bar bg-info" role="progressbar" style="width: {{ ram_usage }}%"
                                                    aria-valuenow="{{ ram_usage }}" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <i class="fa fa-server fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                New Media Pending Requests</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ pending_requests }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>


</div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ManagerApp/prebuild/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'ManagerApp/prebuild/js/sb-admin-2.min.js' %}"></script>


{% endblock page_content %}

MediaStreaming/ManagerApp/templates/ManagerApp/movie_dashboard.html
{% extends 'ManagerApp/dashboard_base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}

{% block page_content %}

<!-- Custom styles for this page -->
<link href="{% static 'ManagerApp/prebuild/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Movies</h1>

        <a href="{% url 'ManagerApp:add_new_movie' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fa fa-plus fa-sm text-white-50"></i> Add Movie</a>
    </div>

    <!-- Content Row -->
    <div class="row">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Latest Movies</h6>
            </div>
            <div class="card-body">
                <div class="row">

                    {% for movie in movies %}
                    <div class="col-xl-2 col-md-3 mb-4">
                        <a href="{% url 'ManagerApp:movie_details' movie_id=movie.id %}" class="col-md">
                            <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 100rem; "
                            src="{% url 'ApiApp:movie_poster' movie_id=movie.id %}?language=en"  onerror="this.onerror=null; this.src='{% url 'ApiApp:movie_poster' movie_id=movie.id %}'">
                            <p class="text-center ont-weight-bold">{{ movie.title }}</p>
                        </a>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>

    </div>



</div>


</div>


</div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ManagerApp/prebuild/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'ManagerApp/prebuild/js/sb-admin-2.min.js' %}"></script>

{% endblock page_content %}

MediaStreaming/ManagerApp/templates/ManagerApp/movie_details.html
{% extends 'ManagerApp/dashboard_base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}

{% block page_content %}

<!-- Basic Card Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{movie.original_title}} </h6>
    </div>
    <div class="card-body">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{{movie.title}}</h1>
            <div class="float-right">
                <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                        class="fa fa-pencil-square-o text-white-50"></i> Edit Movie</a>

                <a href="{% url 'ManagerApp:upload_media_firebase' media_id=movie.id %}?type=movie" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                        class="fa fa-upload text-white-50"></i> Upload Media</a>
            </div>
        </div>


        <div class="float-right">
            <img class="img-fluid px-3 px-sm-4 mt-3 mb-4 " style="width: 20rem; "
                src="{% url 'ApiApp:movie_poster' movie_id=movie.id %}" alt="">
        </div>

        {% for key,values in movie.items %}
        <div class="row">
            <div class="col col-lg-2">
                <h5 class="text-capitalize text-left font-weight-bold">{{key}} :</h5>
            </div>
            <div class="col ">
                <h5 class="text-left">{{values}}</h5>
            </div>

        </div>
        <hr>
        {% endfor %}
    </div>
</div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ManagerApp/prebuild/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'ManagerApp/prebuild/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'ManagerApp/prebuild/js/sb-admin-2.min.js' %}"></script>
{% endblock page_content %}